### ISSUE TITLE
The deployment with Asterisk sometimes failed

### ISSUE THREAD

**Issue by simmkyu** [aws-samples/amazon-chime-sdk-click-to-call#17]
### Describe the bug

The deployment with Asterisk sometimes failed. The AWS CloudFormation outputs the following error message.

```
... failed to create voiceConnectorPhoneNumberChimePhoneNumberChimeCustomResource____
```

### Expected behavior

The deployment with the Asterisk option should succeed.

### Current behavior

Sometimes, the deployment with Asterisk fails with the following error message.

```
... failed to create voiceConnectorPhoneNumberChimePhoneNumberChimeCustomResource____
```

### Steps to Reproduce

1. Install dependencies and run the deployment script.
    ```
    yarn
    ./deploy.sh
    ```
2. The deployment sometimes fails. The CloudFormation performs the rollback step.

### Workaround

Wait for the CloudFormation stack to complete the rollback task and try again until the deployment succeeds.

### Possible root causes

When the deployment failed, the custom resource Lambda functions output the following logs to CloudWatch log groups. 

```
Current status: Processing
Current status: Processing
Current status: Processing
...
Task timed out after 60.06 seconds
...
submit response to cloudformation {   "Status": "FAILED", ...
```

The custom resource failed to create or get a phone number during deployment.

When searching for the keyword `Current status` in this GitHub repository (after running the `./deploy.sh` command at least once), `phonenumbers.py` in the `cdk.out` folder had `Current status` to show the progress of getting a phone number. The `phonenumbers.py` file comes from the [cdk-amazon-chime-resources](https://www.npmjs.com/package/cdk-amazon-chime-resources) NPM dependency.

### AWS SDK version used

cdk 2.27.0

### Operating System and version

macOS 11.6.5

**Comment by schuettc** [comment]
Unfortunately, this deployment is dependent on upstream processes to acquire a phone number and can fail sporadically.

A few things to try:

- In Amazon Chime Console, attempt to acquire a number to verify it is possible in your account.
- Change the State/Area Code/City of the requested number.
- Try to acquire a Toll Free Number instead of Local number.
