### ISSUE TITLE
site/src/cdk-outputs.json file is missing

### ISSUE THREAD

**Issue by AtifTaskin** [aws-samples/amazon-chime-sdk-click-to-call#25]
### Describe the issue

I didn't see cdk-outputs.json file in site/src. Please let me know is it missing in the repo or it will generate by a command.

### Steps to Reproduce

N/A

### Current behavior

ERROR in ./src/Config.js 9:0-44
Module not found: Error: Can't resolve './cdk-outputs.json' in '/Users/vend/Documents/Projects/amazon-chime-sdk-click-to-call/site/src'
resolve './cdk-outputs.json' in '/Users/vend/Documents/Projects/amazon-chime-sdk-click-to-call/site/src'
  using description file: /Users/vend/Documents/Projects/amazon-chime-sdk-click-to-call/site/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /Users/vend/Documents/Projects/amazon-chime-sdk-click-to-call/site/package.json (relative path: ./src/cdk-outputs.json)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/vend/Documents/Projects/amazon-chime-sdk-click-to-call/site/src/cdk-outputs.json doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/vend/Documents/Projects/amazon-chime-sdk-click-to-call/site/src/cdk-outputs.json.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /Users/vend/Documents/Projects/amazon-chime-sdk-click-to-call/site/src/cdk-outputs.json.json doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /Users/vend/Documents/Projects/amazon-chime-sdk-click-to-call/site/src/cdk-outputs.json.wasm doesn't exist
      as directory
        /Users/vend/Documents/Projects/amazon-chime-sdk-click-to-call/site/src/cdk-outputs.json doesn't exist
 @ ./src/App.js 24:0-41 28:18-31 29:14-27
 @ ./src/index.js 3:0-24 9:92-95

webpack 5.73.0 compiled with 1 error in 31711 ms

### AWS SDK version used

"amazon-chime-sdk-js": "3.4.0",

### Operating System and version

macOS Monterey (ver:12.4)

**Comment by schuettc** [comment]
That file should be created when the `yarn launch` command is run.

https://github.com/aws-samples/amazon-chime-sdk-click-to-call/blob/07da19e04b5cd8a3bc0b30427ba6ccde388e54af/.projenrc.js#L28

Previous versions used `./deploy.sh` instead, but in both cases the deploy output should create that file.

**Comment by schuettc** [comment]
That might be a permissions issue with the account you're using to deploy with.  Can you check the IAM permissions on that account?  Or hardcode it here: https://github.com/aws-samples/amazon-chime-sdk-click-to-call/blob/07da19e04b5cd8a3bc0b30427ba6ccde388e54af/src/amazon-chime-sdk-click-to-call.ts#L48

**Comment by schuettc** [comment]
Closing
