### ISSUE TITLE
We facing issue in Cognito user authentication when login Chime front page

### ISSUE THREAD

**Issue by vignesh-Systemadmin** [aws-samples/amazon-chime-sdk-click-to-call#55]
### Describe the issue

Hi Team,

  We able to do deployment from CDK deployment option, once user created from Cognito while login using the credential it saying Error :No current User" in console.( )
  
When deployment Choose the domain option we did in give any specific domain name just enter the option.

Can you please check the 

### Steps to Reproduce

We followed same steps mentioned in github page

### Current behavior

![image](https://user-images.githubusercontent.com/74009159/206856591-feb04bff-bff5-4cad-a69d-dc2499dd3bca.png)

### AWS SDK version used

same in this github repo

### Operating System and version

We deployed same in Amazon linux 2 machine

**Comment by schuettc** [comment]
I just redeployed and could not reproduce.  Could you destroy and try again?  

There are some other Cognito troubleshooting guides that may be worth trying if that doesn't work.

https://github.com/aws-amplify/amplify-js/issues/2702
https://github.com/aws-amplify/amplify-js/issues/8964

**Comment by schuettc** [comment]
Without more detailed logs from the console of the browser, it is hard to say.  However, I have created a dev container within this repo that may help normalize some of the tools used to build.  

I have just redeployed with this dev container (you can use locally via Docker or in a Codespace in GitHub) and had no Cognito issues.  Both in the local dev server and the hosted Cloudfront site.  Can you try with that deployment?

**Comment by schuettc** [comment]
Resolved
